---
certs:
  group: vagrant
  deploy: true
  generate: true
  is_katello_devel: true
katello_devel:
  deployment_dir: /home/vagrant
  user: vagrant
  db_type: postgres
  rvm: true
capsule:
  puppet: true
